<a href="https://colab.research.google.com/github/acamus79/FESAT_Analisis_y_Gestion_de_Datos/blob/main/PracticaClasePython2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1-Generar dos arreglos de tipo entero.
2-Sumarlos entre ellos.
3-Sumar 2 a cada elemento del arreglo.


In [ ]:
import numpy as np


In [ ]:
arreglo1 = np.array([1,3,7,9])
arreglo2 = np.array([2,4,8,10])

In [ ]:
arreglo1+arreglo2

array([ 3,  7, 15, 19])

In [ ]:
arreglo1+2

array([ 3,  5,  9, 11])

In [ ]:
arreglo2+2

array([ 4,  6, 10, 12])